development:
  adapter: postgresql
  encoding: unicode
  database: parser_development
  pool: 5
  timeout: 5000
  username: lukjanenko
  password: liv__210890

test:
  adapter: postgresql
  encoding: unicode
  database: parser_test
  pool: 5
  timeout: 5000
  username: lukjanenko
  password: liv__210890